export {default as Navbar } from './Navbar';
export {default as Feed  }from './Feed';
export {default as VideoDetail } from './VideoDetail';
export {default as ChannelDetail } from './ChannelDetail';
export {default as SearchFeed } from './SearchFeed'; 
export {default as Searchbar } from './Searchbar'; 
export {default as Viedos } from './Viedos'; 
export {default as Sidebar } from './Sidebar'; 
export {default as Channelcard } from './Channelcard'; 
export {default as Videocard } from './Videocard'; 
